CREATE TABLE Game (
		ID INTEGER PRIMARY KEY,
		name TEXT,
		info TEXT,
		image TEXT
		);

CREATE TABLE Tag (
		ID INTEGER PRIMARY KEY, 
		name TEXT
		);

CREATE TABLE GamesTag(
		ID INT NOT NULL UNIQUE PRIMARY KEY,
		gameID INT NOT NULL CONSTRAINT fk_games_id REFERENCES Game(ID),
		tagID  INT NOT NULL CONSTRAINT fk_tag_id REFERENCES Tag(ID)
	);
